### ISSUE TITLE
Load fixture failure.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad#130]
Please do work for this task in a branch called issue-130.
I20170620-08:40:35.957(-10)? Defining 8 TeaserCollection documents.
W20170620-08:40:36.021(-10)? (STDERR) 
W20170620-08:40:36.023(-10)? (STDERR) /Users/carletonmoore/.meteor/packages/meteor-tool/.1.5.0.k8kzrm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170620-08:40:36.024(-10)? (STDERR)                                           throw(ex);
W20170620-08:40:36.025(-10)? (STDERR)                                           ^
W20170620-08:40:36.212(-10)? (STDERR) Error: [Error in getID(): Failed to convert undefined to an ID.]
W20170620-08:40:36.214(-10)? (STDERR)     at OpportunityCollection.getID (imports/api/base/BaseSlugCollection.js:29:13)
W20170620-08:40:36.215(-10)? (STDERR)     at TeaserCollection.define (imports/api/teaser/TeaserCollection.js:63:41)
W20170620-08:40:36.216(-10)? (STDERR)     at imports/api/test/test-utilities.js:33:48
W20170620-08:40:36.217(-10)? (STDERR)     at arrayEach (packages/erasaur_meteor-lodash.js:464:11)
W20170620-08:40:36.217(-10)? (STDERR)     at Function.forEach (packages/erasaur_meteor-lodash.js:7500:11)
W20170620-08:40:36.218(-10)? (STDERR)     at loadCollection (imports/api/test/test-utilities.js:33:5)
W20170620-08:40:36.219(-10)? (STDERR)     at imports/startup/server/initialize-db.js:81:44
W20170620-08:40:36.220(-10)? (STDERR)     at arrayEach (packages/erasaur_meteor-lodash.js:464:11)
W20170620-08:40:36.220(-10)? (STDERR)     at Function.forEach (packages/erasaur_meteor-lodash.js:7500:11)
W20170620-08:40:36.221(-10)? (STDERR)     at loadDatabase (imports/startup/server/initialize-db.js:81:9)
=> Exited with code: 1
W20170620-08:40:42.336(-10)? (STDERR)         
W20170620-08:40:42.337(-10)? (STDERR) /Users/carletonmoore/.meteor/packages/meteor-tool/.1.5.0.k8kzrm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170620-08:40:42.337(-10)? (STDERR)                                           throw(ex);
W20170620-08:40:42.338(-10)? (STDERR)                                           ^
W20170620-08:40:42.518(-10)? (STDERR) Error: [[object Object] is not a defined MentorProfile]
W20170620-08:40:42.519(-10)? (STDERR)     at MentorProfileCollection.findDoc (imports/api/base/BaseCollection.js:73:13)
W20170620-08:40:42.519(-10)? (STDERR)     at imports/api/public-stats/PublicStatsCollection.js:201:38
W20170620-08:40:42.519(-10)? (STDERR)     at arrayMap (packages/erasaur_meteor-lodash.js:586:23)
W20170620-08:40:42.520(-10)? (STDERR)     at Function.map (packages/erasaur_meteor-lodash.js:7707:14)
W20170620-08:40:42.520(-10)? (STDERR)     at PublicStatsCollection.usersMentorsProfessionsList (imports/api/public-stats/PublicStatsCollection.js:200:7)
W20170620-08:40:42.520(-10)? (STDERR)     at imports/api/public-stats/PublicStatsCollection.js:241:9
W20170620-08:40:42.521(-10)? (STDERR)     at arrayMap (packages/erasaur_meteor-lodash.js:586:23)
W20170620-08:40:42.522(-10)? (STDERR)     at Function.map (packages/erasaur_meteor-lodash.js:7707:14)
W20170620-08:40:42.524(-10)? (STDERR)     at PublicStatsCollection.generateStats (imports/api/public-stats/PublicStatsCollection.js:240:9)
W20170620-08:40:42.524(-10)? (STDERR)     at startupPublicStats (imports/startup/server/initialize-db.js:92:15)
=> Exited with code: 1
W20170620-08:40:49.212(-10)? (STDERR)         
W20170620-08:40:49.213(-10)? (STDERR) /Users/carletonmoore/.meteor/packages/meteor-tool/.1.5.0.k8kzrm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170620-08:40:49.214(-10)? (STDERR)                                           throw(ex);
W20170620-08:40:49.216(-10)? (STDERR)                                           ^
W20170620-08:40:49.437(-10)? (STDERR) Error: [[object Object] is not a defined MentorProfile]
W20170620-08:40:49.438(-10)? (STDERR)     at MentorProfileCollection.findDoc (imports/api/base/BaseCollection.js:73:13)
W20170620-08:40:49.440(-10)? (STDERR)     at imports/api/public-stats/PublicStatsCollection.js:201:38
W20170620-08:40:49.442(-10)? (STDERR)     at arrayMap (packages/erasaur_meteor-lodash.js:586:23)
W20170620-08:40:49.442(-10)? (STDERR)     at Function.map (packages/erasaur_meteor-lodash.js:7707:14)
W20170620-08:40:49.443(-10)? (STDERR)     at PublicStatsCollection.usersMentorsProfessionsList (imports/api/public-stats/PublicStatsCollection.js:200:7)
W20170620-08:40:49.443(-10)? (STDERR)     at imports/api/public-stats/PublicStatsCollection.js:241:9
W20170620-08:40:49.443(-10)? (STDERR)     at arrayMap (packages/erasaur_meteor-lodash.js:586:23)
W20170620-08:40:49.444(-10)? (STDERR)     at Function.map (packages/erasaur_meteor-lodash.js:7707:14)
W20170620-08:40:49.470(-10)? (STDERR)     at PublicStatsCollection.generateStats (imports/api/public-stats/PublicStatsCollection.js:240:9)
W20170620-08:40:49.470(-10)? (STDERR)     at startupPublicStats (imports/startup/server/initialize-db.js:92:15)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by cammoore** [comment]
Had to add opportunity to all Teasers.
Used 'generic-project'
