### ISSUE TITLE
AcademicYearUtilities and SemesterUtilities tests fail

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad#235]
Please do work for this task in a branch called issue-235.

1) AcademicYearUtilities #getStudentsCurrentSemesterNumber.:

       AssertionError: expected 12 to equal 11
       + expected - actual

       -12
       +11
  
       at Test.test (imports/api/degree-plan/AcademicYearUtilities.test.js:27:77)
       at run (packages/practicalmeteor:mocha-core/server.js:34:29)
 
   2) SemesterUtilities #upComingSemesters:
 
       AssertionError: expected 6 to equal 7
      + expected - actual
 
       -6
       +7
       
       at Test.test (imports/api/semester/SemesterUtilities.test.js:32:37)
       at run (packages/practicalmeteor:mocha-core/server.js:34:29)

**Comment by cammoore** [comment]
Updated the two tests.
